project:
  type: website
  output-dir: docs

website:
  title: "Assitant to the Regional Manager"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Assignment 1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

