project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Assignment 1.qmd
      - Assignment 4.qmd
      - Assignment 5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

