---
title: "Assignment 4"
---

```{r}
library(ggplot2)

sales_data <- data.frame(
  Fruit = c("Small Apples", "Medium Apples", "Large Apples", "Small Oranges", "Large Oranges"),
  Quantity = c(10, 15, 20, 8, 25),
  Width = c(0.3, 0.5, 0.7, 0.3, 0.7)  # Specify the widths for each bar
)

chart1 <- ggplot(sales_data, aes(x = Fruit, y = Quantity, width = Width)) +
  geom_bar(stat = "identity", fill = "coral") +
  labs(title = "Sales for Fruits of Different Sizes", x = "Fruit", y = "Quantity Sold") +
  theme(text=element_text(size=12,  family="serif"), plot.title = element_text(hjust = 0.5))
  
print(chart1)



```

```{r}

library(gridExtra)
data1 <- data.frame(
  Product = c("A", "B", "C", "D"),
  Revenue = c(5000, 7000, 6500, 3000)
)

data2 <- data.frame(
  Product = c("A", "B", "C", "D"),
  Revenue = c(2000, 5000, 6000, 1000)
)

store1 <- ggplot(data1, aes(x = Product, y = Revenue)) +
  geom_bar(stat = "identity", fill = "midnightblue", alpha = 0.7) +
  labs(title = "Store 1: Product Revenue", x = "Product Type", y = "Revenue (USD)") +
  theme(text=element_text(size=12, family="serif"), plot.title = element_text(hjust = 0.5))

store2 <- ggplot(data2, aes(x = Product, y = Revenue)) +
  geom_bar(stat = "identity", fill = "seagreen4", alpha = 0.7) +
  labs(title = "Store 2: Product Revenue", x = "Product Type", y = "Revenue (USD)") +
  theme(text=element_text(size=12, family="serif"), plot.title = element_text(hjust = 0.5))

combined_chart <- grid.arrange(store1, store2, ncol = 2)
```

```{r}
sales_data <- data.frame(
  Fruit = c("Apples", "Oranges", "Pears", "Kiwis", "Bananas", "Pineapples", "Peaches"),
  Quantity = c(10, 15, 20, 8, 25, 12, 18)
)

chart3 <- ggplot(sales_data, aes(x = Quantity, y = Fruit)) +
  geom_bar(stat = "identity", fill = "darkslategray4") +
  labs(title = "Sales for Different Fruits", x = "Quantity Sold", y = "Type of Fruit") + 
  theme(text=element_text(size=12, family="serif"), plot.title = element_text(hjust = 0.5))

print(chart3)
```

```{r}

hobbies <- c("Baking", "Drawing", "Reading")
data1 <- c(20, 30, 15)
data2 <- c(25, 15, 10)
data3 <- c(15, 10, 13)

data_matrix <- matrix(c(data1, data2, data3), nrow = length(hobbies), byrow = TRUE)

bar_colors <- c("firebrick", "navajowhite3", "darkolivegreen")
bar_labels <- c("Yes", "No", "Maybe")

barplot(data_matrix, beside = TRUE, col = bar_colors, names.arg = hobbies, main = "Survey Reponses to Hobby Interests", xlab = "Hobby Categories", ylab = "Total Number of Reponses", family="serif")

legend("topright", legend = bar_labels, fill = bar_colors)
```
